baseURL = "https://www.abitofme.it"
languageCode = "it-IT"
title = "A B1t 0f Me"
[params]
 instagram = "https://www.instagram.com/organsheroin/"
 github = "https://github.com/gamerita14"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categorie"
