baseURL = "https://www.abitofme.it"
languageCode = "it-IT"
title = "A B1t 0f Me"
enableRobotsTXT = true

[params]
 instagram = "https://www.instagram.com/organsheroin/"
 github = "https://github.com/gamerita14"
 descrizione_meta="Sito Personale, blog, portfolio, uno spazio dove poter mettere i miei pensieri. A B1t 0f Me è un sito statico creato da zero con goHugo, con amore, da Antonio Gorga."

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categorie"
